# based on https://github.com/jonchang/homebrew-biology/blob/master/.github/workflows/upload-bottles.yml
name: Upload bottles.

on:
  push:
    branches:
      - master

jobs:
  upload-bottles:
    runs-on: ubuntu-latest
    container:
      image: homebrew/ubuntu20.04:latest
    env:
      GIT_COMMITTER_NAME: ${{github.event.pusher.name}}
      GIT_COMMITTER_EMAIL: ${{github.event.pusher.email}}
    steps:
      - name: Determine associated pull request
        uses: actions/github-script@0.9.0
        id: pr
        with:
          script: |
            const prs = await github.repos.listPullRequestsAssociatedWithCommit({
              ...context.repo,
              commit_sha: context.payload.head_commit.id
            })
            console.log(prs.data.length + " prs")
            if (prs.data.length === 0) {
              throw "No pull requests are associated with this merge commit."
            }
            core.setOutput("number", prs.data[0].number.toString())
            core.setOutput("head_sha", prs.data[0].head.sha)
      - name: Tap git repository
        run: |
          brew update-reset
          brew tap ${{github.repository}}
      - name: Download workflow artifacts
        uses: Homebrew/actions/download-artifact@master
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build_bottle.yml
          commit: ${{steps.pr.outputs.head_sha}}
          name: bottles
          path: bottles

      - name: Upload bottles
        env:
          HOMEBREW_BOTTLE_DOMAIN: https://dl.bintray.com/mimium-org/
          HOMEBREW_BINTRAY_USER:  tomoyanonymous
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
          HOMEBREW_BINTRAY_URL: https://dl.bintray.com/mimium-org/bottles-mimium
        run: |
          cd bottles
          git config --global user.email "$GIT_COMMITTER_EMAIL"
          git config --global user.name "$GIT_COMMITTER_NAME"
          brew pr-upload --dry-run --root-url=$HOMEBREW_BINTRAY_URL --bintray-org=$HOMEBREW_BINTRAY_USER -v
          brew pr-upload --root-url=$HOMEBREW_BINTRAY_URL --bintray-org=$HOMEBREW_BINTRAY_USER -v

      - name: Push bottle commit
        run: |
          cd $(brew --repo ${{github.repository}})
          git commit --amend --no-edit
          git show --pretty=fuller
          for try in $(seq 5); do
            git fetch
            git rebase origin/master
            if git push https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}} master; then
              break
            else
              sleep 3s
            fi
          done